[tool]
[tool.poetry]
name = "givenergy-modbus"
version = "0.10.1"
homepage = "https://github.com/dewet22/givenergy-modbus"
description = "A python library to access GivEnergy inverters via Modbus TCP, with no dependency on the GivEnergy Cloud."
authors = ["Dewet Diener <givenergy-modbus@dewet.org>"]
readme = "README.md"
license =  "Apache-2.0"
classifiers=[
    'Development Status :: 3 - Alpha',
    'Framework :: Flake8',
    'Framework :: Pytest',
    'Framework :: tox',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: Apache Software License',
    'Natural Language :: English',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Topic :: Home Automation',
    'Topic :: Scientific/Engineering',
    'Topic :: System :: Networking :: Monitoring',
]
packages = [
    { include = "givenergy_modbus" },
    { include = "tests", format = "sdist" },
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
click = "^8.1.2"

black  = { version = "^22.3.0", optional = true}
isort  = { version = "^5.8.0", optional = true}
flake8  = { version = "^4.0.0", optional = true}
flake8-docstrings = { version = "^1.6.0", optional = true }
mypy = {version = "^0.942", optional = true}
pytest  = { version = "^7.1.1", optional = true}
pytest-cov  = { version = "^3.0.0", optional = true}
tox  = { version = "^3.20.1", optional = true}
virtualenv  = { version = "^20.2.2", optional = true}
pip  = { version = "^20.3.1", optional = true}
#mkdocs  = { version = "^1.3.0", optional = true}
#mkdocs-include-markdown-plugin  = { version = "^3.3.0", optional = true}
#mkdocs-material  = { version = "^8.2.9", optional = true}
#mkdocstrings  = { version = "^0.18.1", optional = true}
#mkdocs-material-extensions  = { version = "^1.0.1", optional = true}
twine  = {version = "^4.0.0", optional = true}
#mkdocs-autorefs = {version = "^0.4.1", optional = true}
toml = {version = "^0.10.2", optional = true}
bump2version = {version = "^1.0.1", optional = true}
pymodbus = "^2.5.3"
loguru = ">=0.5.3,<0.7.0"
crccheck = "^1.1"
pydantic = "^1.8.2"
Markdown = {version = "3.3.4", optional = true}
pytkdocs = {version = "^0.16.1", optional = true}
aiofiles = "^0.8.0"
metrology = "^1.3.0"
types-aiofiles = {version = "^0.8.8", extras = ["dev"]}
sentry-sdk = "^1.5.10"
pytest-asyncio = {version = "^0.18.3", extras = ["test"]}
pytest-timeout = {version = "^2.1.0", extras = ["test"]}

[tool.poetry.extras]
test = [
    "pytest",
    "black",
    "isort",
    "mypy",
    "flake8",
    "flake8-docstrings",
    "pytest-cov"
    ]

dev = ["tox", "virtualenv", "pip", "twine", "toml", "bump2version", "twine"]

doc = [
    "mkdocs",
    "mkdocs-include-markdown-plugin",
    "mkdocs-material",
    "mkdocstrings",
    "mkdocs-material-extension",
    "mkdocs-autorefs",
    "Markdown",
    "pytkdocs"
    ]

[tool.poetry.scripts]
givenergy-modbus = 'givenergy_modbus.cli:main'

[tool.poetry.dev-dependencies]
bandit = "^1.7.1"
ipython = "^7.31.1"
flake8 = "^4.0.1"
autopep8 = "^1.6.0"
pre-commit = "^2.16.0"
#poetry = "^1.1.13"
pydocstyle = "^6.1.1"
flake8-typing-imports = "^1.12.0"
[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
skip_gitignore = true
# you can skip files as below
#skip_glob = docs/conf.py

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
