[tool]
[tool.poetry]
name = "givenergy-modbus"
version = "1.0.0"
homepage = "https://github.com/dewet22/givenergy-modbus"
description = "A python library to access GivEnergy inverters via Modbus TCP, with no dependency on the GivEnergy Cloud."
authors = ["Dewet Diener <givenergy-modbus@dewet.org>"]
readme = "README.md"
license =  "Apache-2.0"
classifiers=[
    'Development Status :: 4 - Beta',
    'Framework :: Flake8',
    'Framework :: Pytest',
    'Framework :: tox',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: Apache Software License',
    'Natural Language :: English',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Topic :: Home Automation',
    'Topic :: Scientific/Engineering',
    'Topic :: System :: Networking :: Monitoring',
]
packages = [
    { include = "givenergy_modbus" },
    { include = "tests", format = "sdist" },
]

[tool.poetry.dependencies]
aiofiles = "^0.8.0"
arrow = "^1.2.2"
crccheck = "^1.1"
pydantic = "^1.10.7"
pymodbus = "^2.5.3"
python = ">=3.9,<3.12"
aenum = "^3.1.12"

[tool.poetry.group.dev.dependencies]
bump2version = "^1.0.1"
ipython = "^8.12.0"
pip = "^23.0.1"
pre-commit = "^3.2.2"
pydocstyle = "^6.3.0"
toml = "^0.10.2"
twine = "^4.0.2"
virtualenv = "^20.21.0"
autoflake = "^2.0.2"

[tool.poetry.group.test.dependencies]
autopep8 = "^2.0.2"
bandit = "^1.7.5"
black = "^23.3.0"
flake8 = "^6.0.0"
flake8-docstrings = "^1.7.0"
flake8-typing-imports = "^1.14.0"
isort = "^5.12.0"
mypy = "^1.1.1"
pre-commit = "^3.2.2"
pytest = "^7.2.2"
pytest-asyncio = "^0.21.0"
pytest-cov = "^4.0.0"
pytest-timeout = "^2.1.0"
tox = "^4.4.8"
types-aiofiles = "^23.1.0.1"
types-tabulate = "^0.9.0.2"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.4.2"
mkdocs-autorefs = "^0.4.1"
mkdocs-include-markdown-plugin = "^4.0.4"
mkdocs-material = "^9.1.5"
mkdocs-material-extensions = "^1.1.1"
mkdocstrings = {extras = ["python"], version = "^0.20.0"}
pytkdocs = "^0.16.1"

[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
skip_gitignore = true
# you can skip files as below
#skip_glob = docs/conf.py

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.codespell]
ignore-words-list = "astroid"
skip = "./.*,./poetry.lock"
